version: "3.9"

services:
  redis:
    restart: always
    container_name: redis
    image: redis:latest
  web:
    build: .
    command: >
          bash -c "python manage.py makemigrations
          && python manage.py migrate
          && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: